# Drivers
CONFIG_GPIO=y
CONFIG_ADC=y
CONFIG_PWM=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_PRINTK=y

# Floating point not needed; we use integer math
CONFIG_FPU=n

# Reasonable main stack
CONFIG_MAIN_STACK_SIZE=2048
